name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  ILOC: d:/a/local
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Instalation Location
      shell: cmd
      run: |
        mkdir ${env.$ILOC}
        # set PKG_CONFIG_PATH=d:/a/local/lib/pkgconfig
        # echo "PKG_CONFIG_PATH=d:/a/local/lib/pkgconfig" >> $GITHUB_ENV
    - name: Build and Install zlib
      shell: cmd
      run: |
        curl -sSL -o zlib1212.zip https://zlib.net/zlib1212.zip
        unzip.exe zlib1212.zip
        cd zlib-1.2.12
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$ILOCl -DCMAKE_INSTALL_PREFIX=$ILOC
        cmake --build build --config Release --target install
    - name: Build and Install libpng
      shell: cmd
      run: |
        curl -sSL -o lpng1637.zip https://download.sourceforge.net/libpng/lpng1637.zip
        unzip.exe lpng1637.zip
        cd lpng1637
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=d:/a/local -DCMAKE_INSTALL_PREFIX=d:/a/local
        cmake --build build --config Release --target install

    - name: Build and Install webp
      shell: cmd
      run: |
        git clone --depth 1 https://github.com/webmproject/libwebp.git && cd libwebp
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=d:/a/local -DCMAKE_INSTALL_PREFIX=d:/a/local -DWEBP_BUILD_ANIM_UTILS=OFF
        cmake --build build --config Release --target install
            
    - name: Upload Build Results
      uses: actions/upload-artifact@v2
      with:
        name: tesseract-cmake-win64
        path: $ILOC
        retention-days: 5
