name: cmake_cfg
on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,  ubuntu-22.04, macos-12, windows-latest]

    steps:
      - name: Install dependencies on Linux
        run: |
           sudo apt-get update
           sudo apt-get install -y ninja-build
           sudo apt-get install -y libwebpdemux2 libwebp-dev
           sudo apt-get install -y libopenjp2-7 libopenjp2-7-dev libopenjp2-tools
           sudo apt-get install -y libgif-dev
           cmake --version
        if: runner.os == 'Linux'

      - name: Install dependencies on macOS
        run: |
           brew install ninja
           brew install giflib
           brew install openjpeg
           brew install webp
           cmake --version
        if: runner.os == 'macOS'

      - name: Checkout Source
        uses: actions/checkout@v3
        # with:
             # submodules: recursive

      - name: get-leptonica
        run: |
          git clone https://github.com/zdenop/leptonica.git
          cd leptonica
          cmake -B ${{github.workspace}}/build -DBUILD_PROG=OFF -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON 
          # -DSTRICT_CONF=ON

      - name: build-leptonica
        run: |
          cd leptonica
          sudo cmake --build ${{github.workspace}}/build --config Release --target install

      - name: Display Compiler Version
        run: |
            cd leptonica
             git log -3 --pretty=format:'%h %ad %s | %an'
        if: always()
