name: macos
on:
  #push:
  workflow_dispatch:

jobs:
  basictests:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: macos-11-clang-12-cmake, os: macos-11, cxx: clang++ } # default
          - { name: macos-11-gcc-9-cmake, os: macos-11, cxx: g++-9 } #installed         
    steps:
      - name: Install dependencies on macOS
        run: |
           brew install autoconf automake
           brew install leptonica
           brew install libiconv
           brew install libarchive
           brew install pango
           brew install icu4c && brew link icu4c
           brew install cabextract
           brew install ninja
           brew install tesseract           
           ninja --version
           cmake --version
           brew list leptonica
           pkg-config --cflags lept

      - name: Checkout Source
        uses: actions/checkout@v3
        with:
             submodules: recursive

      - name: Build and run basicapitest (macOS)
        run: |
             export "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/build/inst/lib/pkgconfig/:$(brew --prefix)/opt/libarchive/lib/pkgconfig:$(brew --prefix)/Library/Homebrew/os/mac/pkgconfig/11:$PKG_CONFIG_PATH"
             pkg-config --cflags --libs tesseract lept libarchive libcurl
             ${{ matrix.config.cxx }} -o basicapitest testing/basicapitest.cpp "-I$GITHUB_WORKSPACE/build/inst/include" "-L$GITHUB_WORKSPACE/build/inst/lib" $(pkg-config --cflags --libs tesseract lept libarchive libcurl) -pthread -std=c++11
             ./basicapitest
        if: runner.os == 'macOS'
        
      - name: Display Compiler Version
        run: |
             ${{ matrix.config.cxx }} --version
             git log -3 --pretty=format:'%h %ad %s | %an'
        if: always()
